const dogToys = [
  {
    id: 1,
    name: "Rubber Chew Toy",
    price: 12.99,
    description: "Durable rubber chew toy for aggressive chewers.",
    image: "/images/toys/rubber-chew-toy.jpg",
    category: "dog",
  },
  {
    id: 2,
    name: "Squeaky Plush Toy",
    price: 15.49,
    description: "Soft plush toy with a fun squeaker inside.",
    image: "/images/toys/squeaky-plush-toy.jpg",
    category: "dog",
  },
  {
    id: 3,
    name: "Rope Tug Toy",
    price: 9.99,
    description: "Strong rope toy great for tug-of-war games.",
    image: "/images/toys/rope-tug-toy.jpg",
    category: "dog",
  },
  {
    id: 4,
    name: "Tennis Ball Set",
    price: 8.5,
    description: "Set of 3 durable tennis balls for fetch fun.",
    image: "/images/toys/tennis-ball-set.jpg",
    category: "dog",
  },
  {
    id: 5,
    name: "Interactive Puzzle Toy",
    price: 19.99,
    description: "Stimulates your dog's mind with treat puzzles.",
    image: "/images/toys/interactive-puzzle-toy.jpg",
    category: "dog",
  },
  {
    id: 6,
    name: "Rubber Bone Toy",
    price: 14.25,
    description: "Chew-resistant rubber bone for hours of fun.",
    image: "/images/toys/rubber-bone-toy.jpg",
    category: "dog",
  },
  {
    id: 7,
    name: "Frisbee Disc",
    price: 11.0,
    description: "Lightweight and flexible frisbee for active dogs.",
    image: "/images/toys/frisbee-disc.jpg",
    category: "dog",
  },
  {
    id: 8,
    name: "Knotted Ball Toy",
    price: 7.99,
    description: "Soft ball with knotted threads for chewing.",
    image: "/images/toys/knotted-ball-toy.jpg",
    category: "dog",
  },
  {
    id: 9,
    name: "Plush Squeaky Bone",
    price: 13.5,
    description: "Plush bone with squeaker to keep dogs entertained.",
    image: "/images/toys/plush-squeaky-bone.jpg",
    category: "dog",
  },
  {
    id: 10,
    name: "Treat Dispensing Toy",
    price: 21.0,
    description: "Toy that dispenses treats as your dog plays.",
    image: "/images/toys/treat-dispensing-toy.jpg",
    category: "dog",
  },
];

export default dogToys;
